# ******* WARNING - AUTO GENERATED CODE - DO NOT EDIT *******
from .VmomiSupport import CreateDataType, CreateManagedType
from .VmomiSupport import CreateEnumType
from .VmomiSupport import AddVersion, AddVersionParent
from .VmomiSupport import AddBreakingChangesInfo
from .VmomiSupport import F_LINK, F_LINKABLE
from .VmomiSupport import F_OPTIONAL, F_SECRET
from .VmomiSupport import newestVersions, stableVersions
from .VmomiSupport import publicVersions, dottedVersions
from .VmomiSupport import oldestVersions

AddBreakingChangesInfo("vmcore-main", "b2btest", 1)
AddBreakingChangesInfo("vim-main", "b2btest", 13)
AddVersion("b2btest.version.stable", "b2btest35", "s39B66", 0, "b2btest35")
AddVersion("vmodl.query.version.version1", "", "", 0, "vim25")
AddVersion("b2btest.version.unstable", "b2btest35", "uC1CD4", 0, "b2btest35")
AddVersion("vmodl.version.version0", "", "", 0, "vim25")
AddVersion("b2btest.version.version1", "b2btest35", "1.0", 0, "b2btest35")
AddVersion("b2btest.version.version3", "b2btest35", "3.0", 1, "b2btest35")
AddVersion("b2btest.version.version2", "b2btest35", "2.0", 0, "b2btest35")
AddVersion("b2btest.version.disabled", "b2btest35", "", 0, "b2btest35")
AddVersionParent("b2btest.version.stable", "b2btest.version.stable")
AddVersionParent("b2btest.version.stable", "vmodl.query.version.version1")
AddVersionParent("b2btest.version.stable", "vmodl.version.version0")
AddVersionParent("b2btest.version.stable", "b2btest.version.version1")
AddVersionParent("b2btest.version.stable", "b2btest.version.version3")
AddVersionParent("b2btest.version.stable", "b2btest.version.version2")
AddVersionParent("vmodl.query.version.version1", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version1", "vmodl.version.version0")
AddVersionParent("b2btest.version.unstable", "b2btest.version.stable")
AddVersionParent("b2btest.version.unstable", "vmodl.query.version.version1")
AddVersionParent("b2btest.version.unstable", "b2btest.version.unstable")
AddVersionParent("b2btest.version.unstable", "vmodl.version.version0")
AddVersionParent("b2btest.version.unstable", "b2btest.version.version1")
AddVersionParent("b2btest.version.unstable", "b2btest.version.version3")
AddVersionParent("b2btest.version.unstable", "b2btest.version.version2")
AddVersionParent("vmodl.version.version0", "vmodl.version.version0")
AddVersionParent("b2btest.version.version1", "vmodl.query.version.version1")
AddVersionParent("b2btest.version.version1", "vmodl.version.version0")
AddVersionParent("b2btest.version.version1", "b2btest.version.version1")
AddVersionParent("b2btest.version.version3", "vmodl.query.version.version1")
AddVersionParent("b2btest.version.version3", "vmodl.version.version0")
AddVersionParent("b2btest.version.version3", "b2btest.version.version1")
AddVersionParent("b2btest.version.version3", "b2btest.version.version3")
AddVersionParent("b2btest.version.version3", "b2btest.version.version2")
AddVersionParent("b2btest.version.version2", "vmodl.query.version.version1")
AddVersionParent("b2btest.version.version2", "vmodl.version.version0")
AddVersionParent("b2btest.version.version2", "b2btest.version.version1")
AddVersionParent("b2btest.version.version2", "b2btest.version.version2")
AddVersionParent("b2btest.version.disabled", "b2btest.version.stable")
AddVersionParent("b2btest.version.disabled", "vmodl.query.version.version1")
AddVersionParent("b2btest.version.disabled", "b2btest.version.unstable")
AddVersionParent("b2btest.version.disabled", "vmodl.version.version0")
AddVersionParent("b2btest.version.disabled", "b2btest.version.version1")
AddVersionParent("b2btest.version.disabled", "b2btest.version.version3")
AddVersionParent("b2btest.version.disabled", "b2btest.version.version2")
AddVersionParent("b2btest.version.disabled", "b2btest.version.disabled")

newestVersions.Add("b2btest.version.unstable")
stableVersions.Add("b2btest.version.stable")
publicVersions.Add("b2btest.version.version3")
dottedVersions.Add("b2btest.version.version3")
oldestVersions.Add("b2btest.version.version1")

CreateDataType("b2btest.DataObject1", "DataObject1", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "byte", "b2btest.version.version1", 0), ("property2", "byte[]", "b2btest.version.version1", 0)])
CreateDataType("b2btest.DataObject10", "DataObject10", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "int", "b2btest.version.version1", 0), ("property2", "int", "b2btest.version.unstable", F_OPTIONAL)])
CreateDataType("b2btest.DataObject11", "DataObject11", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "int", "b2btest.version.version1", 0), ("property2", "int", "b2btest.version.stable", F_OPTIONAL)])
CreateDataType("b2btest.DataObject12", "DataObject12", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "int", "b2btest.version.version1", 0), ("property2", "int", "b2btest.version.unstable", F_OPTIONAL)])
CreateDataType("b2btest.DataObject13", "DataObject13", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "int", "b2btest.version.version1", 0), ("property2", "int", "b2btest.version.stable", F_OPTIONAL)])
CreateDataType("b2btest.DataObject14", "DataObject14", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "int", "b2btest.version.version1", 0), ("property2", "int", "b2btest.version.stable", F_OPTIONAL), ("property3", "int", "b2btest.version.stable", F_OPTIONAL)])
CreateDataType("b2btest.DataObject15", "DataObject15", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "int", "b2btest.version.stable", 0), ("property2", "int", "b2btest.version.stable", F_OPTIONAL)])
CreateDataType("b2btest.DataObject16", "DataObject16", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "int", "b2btest.version.stable", 0), ("property2", "int", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject17", "DataObject17", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "int", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject18", "DataObject18", "b2btest.DataObject17", "b2btest.version.stable", [("property4", "int", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject19", "DataObject19", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "int", "b2btest.version.stable", 0), ("property22", "int", "b2btest.version.stable", 0), ("property33", "int", "b2btest.version.stable", F_OPTIONAL)])
CreateDataType("b2btest.DataObject2", "DataObject2", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "vmodl.TypeName", "b2btest.version.version1", 0), ("property2", "vmodl.TypeName[]", "b2btest.version.version1", 0)])
CreateDataType("b2btest.DataObject20", "DataObject20", "b2btest.DataObject19", "b2btest.version.stable", [("property4", "int", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject21", "DataObject21", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "int", "b2btest.version.stable", 0), ("property2", "int", "b2btest.version.stable", 0), ("property3", "int", "b2btest.version.stable", F_OPTIONAL)])
CreateDataType("b2btest.DataObject22", "DataObject22", "b2btest.DataObject21", "b2btest.version.stable", [("property4", "int", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject23", "DataObject23", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "int", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject24", "DataObject24", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "int", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject25", "DataObject25", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "string", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject26", "DataObject26", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "long", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject27", "DataObject27", "b2btest.DataObject26", "b2btest.version.stable", [("property2", "string", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject28", "DataObject28", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "b2btest.DataObject28.Info2", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject28.Info1", "DataObject28Info1", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "int", "b2btest.version.version1", 0)])
CreateDataType("b2btest.DataObject28.Info2", "DataObject28Info2", "vmodl.DynamicData", "b2btest.version.version1", [("property2", "int", "b2btest.version.version1", 0)])
CreateDataType("b2btest.DataObject29", "DataObject29", "b2btest.DataObject28", "b2btest.version.stable", [("property2", "b2btest.DataObject28.Info1", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject30", "DataObject30", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "b2btest.DataObject30.Base1", "b2btest.version.stable", 0), ("property2", "b2btest.DataObject30.Base2", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject30.Base1", "DataObject30Base1", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "int", "b2btest.version.version1", 0)])
CreateDataType("b2btest.DataObject30.Base2", "DataObject30Base2", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "int", "b2btest.version.version1", 0), ("property2", "int", "b2btest.version.version1", 0)])
CreateDataType("b2btest.DataObject30.Derived1", "DataObject30Derived1", "b2btest.DataObject30.Base1", "b2btest.version.version1", [("property3", "int", "b2btest.version.version1", 0)])
CreateDataType("b2btest.DataObject30.Derived2", "DataObject30Derived2", "b2btest.DataObject30.Base2", "b2btest.version.version1", [("property3", "int", "b2btest.version.version1", 0)])
CreateDataType("b2btest.DataObject31", "DataObject31", "b2btest.DataObject30", "b2btest.version.stable", [("property3", "b2btest.DataObject30.Base1", "b2btest.version.stable", 0), ("property4", "b2btest.DataObject30.Base2", "b2btest.version.stable", 0)])
CreateDataType("b2btest.DataObject4", "DataObject4", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "b2btest.ManagedObject1", "b2btest.version.version1", 0), ("property2", "b2btest.ManagedObject1[]", "b2btest.version.version1", 0)])
CreateDataType("b2btest.DataObject5", "DataObject5", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "vmodl.ManagedObject", "b2btest.version.version1", 0), ("property2", "vmodl.ManagedObject[]", "b2btest.version.version1", 0)])
CreateDataType("b2btest.DataObject6", "DataObject6", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "b2btest.DataObject1", "b2btest.version.version1", 0), ("property2", "b2btest.DataObject1[]", "b2btest.version.version1", 0)])
CreateDataType("b2btest.DataObject7", "DataObject7", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "vmodl.DataObject", "b2btest.version.version1", 0), ("property2", "vmodl.DataObject[]", "b2btest.version.version1", 0)])
CreateDataType("b2btest.DataObject8", "DataObject8", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "anyType", "b2btest.version.version1", 0), ("property2", "anyType[]", "b2btest.version.version1", F_OPTIONAL)])
CreateDataType("b2btest.DataObject9", "DataObject9", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "int", "b2btest.version.version1", 0), ("property2", "int", "b2btest.version.stable", F_OPTIONAL)])
CreateDataType("b2btest.DataObjectE1", "DataObjectE1", "vmodl.DynamicData", "b2btest.version.stable", [("type", "string", "b2btest.version.stable", 0)])
CreateEnumType("b2btest.DataObjectE1.Type", "DataObjectE1Type", "b2btest.version.version1", ["ONE", "TWO"])
CreateDataType("b2btest.DataObjectE2", "DataObjectE2", "vmodl.DynamicData", "b2btest.version.stable", None)
CreateDataType("b2btest.DataObjectE3", "DataObjectE3", "vmodl.DynamicData", "b2btest.version.stable", [("type", "string", "b2btest.version.stable", 0)])
CreateEnumType("b2btest.DataObjectE3.Type2", "DataObjectE3Type2", "b2btest.version.version1", ["ONE", "TWO"])
CreateDataType("b2btest.DataObjectE4", "DataObjectE4", "vmodl.DynamicData", "b2btest.version.stable", [("type", "string", "b2btest.version.stable", 0)])
CreateEnumType("b2btest.DataObjectE4.Type", "DataObjectE4Type", "b2btest.version.version1", ["ONE", "TWO"])
CreateDataType("b2btest.DataObjectE5", "DataObjectE5", "vmodl.DynamicData", "b2btest.version.stable", [("type", "string", "b2btest.version.stable", 0)])
CreateEnumType("b2btest.DataObjectE5.Type", "DataObjectE5Type", "b2btest.version.version1", ["ONE", "TWO"])
CreateEnumType("b2btest.Enum1", "Enum1", "b2btest.version.version1", ["ONE", "TWO"])
CreateEnumType("b2btest.Enum2", "Enum2", "b2btest.version.stable", ["TWO", "THREE"])
CreateDataType("b2btest.HLUIDo1", "HLUIDo1", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "int", "b2btest.version.stable", 0)])
CreateDataType("b2btest.HLUIDo2", "HLUIDo2", "b2btest.HLUIDo1", "b2btest.version.stable", [("property4", "int", "b2btest.version.stable", 0)])
CreateDataType("b2btest.HLUIDo3", "HLUIDo3", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "int", "b2btest.version.stable", 0), ("property22", "int", "b2btest.version.stable", 0), ("property33", "int", "b2btest.version.stable", F_OPTIONAL)])
CreateDataType("b2btest.HLUIDo4", "HLUIDo4", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "int", "b2btest.version.stable", 0), ("property2", "int", "b2btest.version.stable", 0), ("property3", "int", "b2btest.version.stable", F_OPTIONAL)])
CreateDataType("b2btest.HLUIDo5", "HLUIDo5", "b2btest.HLUIDo4", "b2btest.version.stable", [("property4", "int", "b2btest.version.stable", 0)])
CreateDataType("b2btest.HLUIDo6", "HLUIDo6", "vmodl.DynamicData", "b2btest.version.stable", [("property1", "int", "b2btest.version.stable", 0)])
CreateManagedType("b2btest.ManagedObject1", "ManagedObject1", "vmodl.ManagedObject", "b2btest.version.version1", None, [("task1", "ManagedObject1_Task1_Task", "b2btest.version.version1", (), (0, "b2btest.Task", "void"), None, None)])
CreateManagedType("b2btest.ManagedObject2", "ManagedObject2", "vmodl.ManagedObject", "b2btest.version.version1", None, [("task1", "ManagedObject2_Task1_Task", "b2btest.version.version1", (), (0, "b2btest.Task", "void"), None, None)])
CreateDataType("b2btest.Task", "Task", "vmodl.DynamicData", "b2btest.version.version1", None)
CreateDataType("b2btest.DataObject3", "DataObject3", "vmodl.DynamicData", "b2btest.version.version1", [("property1", "b2btest.Enum1", "b2btest.version.version1", 0), ("property2", "b2btest.Enum1[]", "b2btest.version.version1", 0)])
