# ******* WARNING - AUTO GENERATED CODE - DO NOT EDIT *******
from .VmomiSupport import CreateDataType, CreateManagedType
from .VmomiSupport import CreateEnumType
from .VmomiSupport import AddVersion, AddVersionParent
from .VmomiSupport import AddBreakingChangesInfo
from .VmomiSupport import F_LINK, F_LINKABLE
from .VmomiSupport import F_OPTIONAL, F_SECRET
from .VmomiSupport import newestVersions, stableVersions
from .VmomiSupport import publicVersions, dottedVersions
from .VmomiSupport import oldestVersions

AddVersion("vmodl.query.version.version4", "", "", 0, "vim25")
AddVersion("vmodl.query.version.version3", "", "", 0, "vim25")
AddVersion("vmodl.query.version.version2", "", "", 0, "vim25")
AddVersion("vmodl.query.version.version1", "", "", 0, "vim25")
AddVersion("vim.version.version8", "vim25", "5.1", 0, "vim25")
AddVersion("cis.data.provider.version.version1", "cis.data.provider", "1.0", 0, "")
AddVersion("vim.version.version9", "vim25", "5.5", 0, "vim25")
AddVersion("vim.version.version6", "vim25", "4.1", 0, "vim25")
AddVersion("vim.version.version7", "vim25", "5.0", 0, "vim25")
AddVersion("vim.version.version1", "vim2", "2.0", 0, "vim25")
AddVersion("vim.version.version4", "vim25", "2.5u2server", 0, "vim25")
AddVersion("vim.version.version5", "vim25", "4.0", 0, "vim25")
AddVersion("vim.version.version2", "vim25", "2.5", 0, "vim25")
AddVersion("vim.version.version3", "vim25", "2.5u2", 0, "vim25")
AddVersion("vmodl.version.version0", "", "", 0, "vim25")
AddVersion("vmodl.version.version1", "", "", 0, "vim25")
AddVersion("vmodl.version.version2", "", "", 0, "vim25")
AddVersion("vmodl.reflect.version.version1", "reflect", "1.0", 0, "reflect")
AddVersion("vmodl.reflect.version.version2", "reflect", "2.0", 0, "reflect")
AddVersion("vim.version.version13", "vim25", "6.7.1", 0, "vim25")
AddVersion("cis.data.provider.version.version12", "cis.data.provider", "6.6", 0, "")
AddVersion("cis.data.provider.version.version13", "cis.data.provider", "6.9", 0, "")
AddVersion("vim.version.version10", "vim25", "6.0", 0, "vim25")
AddVersion("vim.version.version11", "vim25", "6.5", 0, "vim25")
AddVersion("vim.version.version12", "vim25", "6.7", 0, "vim25")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version4")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version3")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version2")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version4", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version4", "vmodl.version.version1")
AddVersionParent("vmodl.query.version.version4", "vmodl.version.version2")
AddVersionParent("vmodl.query.version.version3", "vmodl.query.version.version3")
AddVersionParent("vmodl.query.version.version3", "vmodl.query.version.version2")
AddVersionParent("vmodl.query.version.version3", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version3", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version3", "vmodl.version.version1")
AddVersionParent("vmodl.query.version.version2", "vmodl.query.version.version2")
AddVersionParent("vmodl.query.version.version2", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version2", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version2", "vmodl.version.version1")
AddVersionParent("vmodl.query.version.version1", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version1", "vmodl.version.version0")
AddVersionParent("vim.version.version8", "vmodl.query.version.version4")
AddVersionParent("vim.version.version8", "vmodl.query.version.version3")
AddVersionParent("vim.version.version8", "vmodl.query.version.version2")
AddVersionParent("vim.version.version8", "vmodl.query.version.version1")
AddVersionParent("vim.version.version8", "vim.version.version8")
AddVersionParent("vim.version.version8", "vim.version.version6")
AddVersionParent("vim.version.version8", "vim.version.version7")
AddVersionParent("vim.version.version8", "vim.version.version1")
AddVersionParent("vim.version.version8", "vim.version.version4")
AddVersionParent("vim.version.version8", "vim.version.version5")
AddVersionParent("vim.version.version8", "vim.version.version2")
AddVersionParent("vim.version.version8", "vim.version.version3")
AddVersionParent("vim.version.version8", "vmodl.version.version0")
AddVersionParent("vim.version.version8", "vmodl.version.version1")
AddVersionParent("vim.version.version8", "vmodl.version.version2")
AddVersionParent("vim.version.version8", "vmodl.reflect.version.version1")
AddVersionParent("cis.data.provider.version.version1", "vmodl.query.version.version4")
AddVersionParent("cis.data.provider.version.version1", "vmodl.query.version.version3")
AddVersionParent("cis.data.provider.version.version1", "vmodl.query.version.version2")
AddVersionParent("cis.data.provider.version.version1", "vmodl.query.version.version1")
AddVersionParent("cis.data.provider.version.version1", "vim.version.version8")
AddVersionParent("cis.data.provider.version.version1", "cis.data.provider.version.version1")
AddVersionParent("cis.data.provider.version.version1", "vim.version.version9")
AddVersionParent("cis.data.provider.version.version1", "vim.version.version6")
AddVersionParent("cis.data.provider.version.version1", "vim.version.version7")
AddVersionParent("cis.data.provider.version.version1", "vim.version.version1")
AddVersionParent("cis.data.provider.version.version1", "vim.version.version4")
AddVersionParent("cis.data.provider.version.version1", "vim.version.version5")
AddVersionParent("cis.data.provider.version.version1", "vim.version.version2")
AddVersionParent("cis.data.provider.version.version1", "vim.version.version3")
AddVersionParent("cis.data.provider.version.version1", "vmodl.version.version0")
AddVersionParent("cis.data.provider.version.version1", "vmodl.version.version1")
AddVersionParent("cis.data.provider.version.version1", "vmodl.version.version2")
AddVersionParent("cis.data.provider.version.version1", "vmodl.reflect.version.version1")
AddVersionParent("cis.data.provider.version.version1", "vmodl.reflect.version.version2")
AddVersionParent("cis.data.provider.version.version1", "vim.version.version10")
AddVersionParent("cis.data.provider.version.version1", "vim.version.version11")
AddVersionParent("vim.version.version9", "vmodl.query.version.version4")
AddVersionParent("vim.version.version9", "vmodl.query.version.version3")
AddVersionParent("vim.version.version9", "vmodl.query.version.version2")
AddVersionParent("vim.version.version9", "vmodl.query.version.version1")
AddVersionParent("vim.version.version9", "vim.version.version8")
AddVersionParent("vim.version.version9", "vim.version.version9")
AddVersionParent("vim.version.version9", "vim.version.version6")
AddVersionParent("vim.version.version9", "vim.version.version7")
AddVersionParent("vim.version.version9", "vim.version.version1")
AddVersionParent("vim.version.version9", "vim.version.version4")
AddVersionParent("vim.version.version9", "vim.version.version5")
AddVersionParent("vim.version.version9", "vim.version.version2")
AddVersionParent("vim.version.version9", "vim.version.version3")
AddVersionParent("vim.version.version9", "vmodl.version.version0")
AddVersionParent("vim.version.version9", "vmodl.version.version1")
AddVersionParent("vim.version.version9", "vmodl.version.version2")
AddVersionParent("vim.version.version9", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version6", "vmodl.query.version.version3")
AddVersionParent("vim.version.version6", "vmodl.query.version.version2")
AddVersionParent("vim.version.version6", "vmodl.query.version.version1")
AddVersionParent("vim.version.version6", "vim.version.version6")
AddVersionParent("vim.version.version6", "vim.version.version1")
AddVersionParent("vim.version.version6", "vim.version.version4")
AddVersionParent("vim.version.version6", "vim.version.version5")
AddVersionParent("vim.version.version6", "vim.version.version2")
AddVersionParent("vim.version.version6", "vim.version.version3")
AddVersionParent("vim.version.version6", "vmodl.version.version0")
AddVersionParent("vim.version.version6", "vmodl.version.version1")
AddVersionParent("vim.version.version7", "vmodl.query.version.version4")
AddVersionParent("vim.version.version7", "vmodl.query.version.version3")
AddVersionParent("vim.version.version7", "vmodl.query.version.version2")
AddVersionParent("vim.version.version7", "vmodl.query.version.version1")
AddVersionParent("vim.version.version7", "vim.version.version6")
AddVersionParent("vim.version.version7", "vim.version.version7")
AddVersionParent("vim.version.version7", "vim.version.version1")
AddVersionParent("vim.version.version7", "vim.version.version4")
AddVersionParent("vim.version.version7", "vim.version.version5")
AddVersionParent("vim.version.version7", "vim.version.version2")
AddVersionParent("vim.version.version7", "vim.version.version3")
AddVersionParent("vim.version.version7", "vmodl.version.version0")
AddVersionParent("vim.version.version7", "vmodl.version.version1")
AddVersionParent("vim.version.version7", "vmodl.version.version2")
AddVersionParent("vim.version.version7", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version1", "vmodl.query.version.version1")
AddVersionParent("vim.version.version1", "vim.version.version1")
AddVersionParent("vim.version.version1", "vmodl.version.version0")
AddVersionParent("vim.version.version4", "vmodl.query.version.version1")
AddVersionParent("vim.version.version4", "vim.version.version1")
AddVersionParent("vim.version.version4", "vim.version.version4")
AddVersionParent("vim.version.version4", "vim.version.version2")
AddVersionParent("vim.version.version4", "vim.version.version3")
AddVersionParent("vim.version.version4", "vmodl.version.version0")
AddVersionParent("vim.version.version5", "vmodl.query.version.version2")
AddVersionParent("vim.version.version5", "vmodl.query.version.version1")
AddVersionParent("vim.version.version5", "vim.version.version1")
AddVersionParent("vim.version.version5", "vim.version.version4")
AddVersionParent("vim.version.version5", "vim.version.version5")
AddVersionParent("vim.version.version5", "vim.version.version2")
AddVersionParent("vim.version.version5", "vim.version.version3")
AddVersionParent("vim.version.version5", "vmodl.version.version0")
AddVersionParent("vim.version.version5", "vmodl.version.version1")
AddVersionParent("vim.version.version2", "vmodl.query.version.version1")
AddVersionParent("vim.version.version2", "vim.version.version1")
AddVersionParent("vim.version.version2", "vim.version.version2")
AddVersionParent("vim.version.version2", "vmodl.version.version0")
AddVersionParent("vim.version.version3", "vmodl.query.version.version1")
AddVersionParent("vim.version.version3", "vim.version.version1")
AddVersionParent("vim.version.version3", "vim.version.version2")
AddVersionParent("vim.version.version3", "vim.version.version3")
AddVersionParent("vim.version.version3", "vmodl.version.version0")
AddVersionParent("vmodl.version.version0", "vmodl.version.version0")
AddVersionParent("vmodl.version.version1", "vmodl.version.version0")
AddVersionParent("vmodl.version.version1", "vmodl.version.version1")
AddVersionParent("vmodl.version.version2", "vmodl.version.version0")
AddVersionParent("vmodl.version.version2", "vmodl.version.version1")
AddVersionParent("vmodl.version.version2", "vmodl.version.version2")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.version.version0")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.version.version1")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.version.version2")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.reflect.version.version1")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.version.version0")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.version.version1")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.version.version2")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.reflect.version.version1")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version13", "vmodl.query.version.version4")
AddVersionParent("vim.version.version13", "vmodl.query.version.version3")
AddVersionParent("vim.version.version13", "vmodl.query.version.version2")
AddVersionParent("vim.version.version13", "vmodl.query.version.version1")
AddVersionParent("vim.version.version13", "vim.version.version8")
AddVersionParent("vim.version.version13", "vim.version.version9")
AddVersionParent("vim.version.version13", "vim.version.version6")
AddVersionParent("vim.version.version13", "vim.version.version7")
AddVersionParent("vim.version.version13", "vim.version.version1")
AddVersionParent("vim.version.version13", "vim.version.version4")
AddVersionParent("vim.version.version13", "vim.version.version5")
AddVersionParent("vim.version.version13", "vim.version.version2")
AddVersionParent("vim.version.version13", "vim.version.version3")
AddVersionParent("vim.version.version13", "vmodl.version.version0")
AddVersionParent("vim.version.version13", "vmodl.version.version1")
AddVersionParent("vim.version.version13", "vmodl.version.version2")
AddVersionParent("vim.version.version13", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version13", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version13", "vim.version.version13")
AddVersionParent("vim.version.version13", "vim.version.version10")
AddVersionParent("vim.version.version13", "vim.version.version11")
AddVersionParent("vim.version.version13", "vim.version.version12")
AddVersionParent("cis.data.provider.version.version12", "vmodl.query.version.version4")
AddVersionParent("cis.data.provider.version.version12", "vmodl.query.version.version3")
AddVersionParent("cis.data.provider.version.version12", "vmodl.query.version.version2")
AddVersionParent("cis.data.provider.version.version12", "vmodl.query.version.version1")
AddVersionParent("cis.data.provider.version.version12", "vim.version.version8")
AddVersionParent("cis.data.provider.version.version12", "cis.data.provider.version.version1")
AddVersionParent("cis.data.provider.version.version12", "vim.version.version9")
AddVersionParent("cis.data.provider.version.version12", "vim.version.version6")
AddVersionParent("cis.data.provider.version.version12", "vim.version.version7")
AddVersionParent("cis.data.provider.version.version12", "vim.version.version1")
AddVersionParent("cis.data.provider.version.version12", "vim.version.version4")
AddVersionParent("cis.data.provider.version.version12", "vim.version.version5")
AddVersionParent("cis.data.provider.version.version12", "vim.version.version2")
AddVersionParent("cis.data.provider.version.version12", "vim.version.version3")
AddVersionParent("cis.data.provider.version.version12", "vmodl.version.version0")
AddVersionParent("cis.data.provider.version.version12", "vmodl.version.version1")
AddVersionParent("cis.data.provider.version.version12", "vmodl.version.version2")
AddVersionParent("cis.data.provider.version.version12", "vmodl.reflect.version.version1")
AddVersionParent("cis.data.provider.version.version12", "vmodl.reflect.version.version2")
AddVersionParent("cis.data.provider.version.version12", "cis.data.provider.version.version12")
AddVersionParent("cis.data.provider.version.version12", "vim.version.version10")
AddVersionParent("cis.data.provider.version.version12", "vim.version.version11")
AddVersionParent("cis.data.provider.version.version12", "vim.version.version12")
AddVersionParent("cis.data.provider.version.version13", "vmodl.query.version.version4")
AddVersionParent("cis.data.provider.version.version13", "vmodl.query.version.version3")
AddVersionParent("cis.data.provider.version.version13", "vmodl.query.version.version2")
AddVersionParent("cis.data.provider.version.version13", "vmodl.query.version.version1")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version8")
AddVersionParent("cis.data.provider.version.version13", "cis.data.provider.version.version1")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version9")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version6")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version7")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version1")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version4")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version5")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version2")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version3")
AddVersionParent("cis.data.provider.version.version13", "vmodl.version.version0")
AddVersionParent("cis.data.provider.version.version13", "vmodl.version.version1")
AddVersionParent("cis.data.provider.version.version13", "vmodl.version.version2")
AddVersionParent("cis.data.provider.version.version13", "vmodl.reflect.version.version1")
AddVersionParent("cis.data.provider.version.version13", "vmodl.reflect.version.version2")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version13")
AddVersionParent("cis.data.provider.version.version13", "cis.data.provider.version.version12")
AddVersionParent("cis.data.provider.version.version13", "cis.data.provider.version.version13")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version10")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version11")
AddVersionParent("cis.data.provider.version.version13", "vim.version.version12")
AddVersionParent("vim.version.version10", "vmodl.query.version.version4")
AddVersionParent("vim.version.version10", "vmodl.query.version.version3")
AddVersionParent("vim.version.version10", "vmodl.query.version.version2")
AddVersionParent("vim.version.version10", "vmodl.query.version.version1")
AddVersionParent("vim.version.version10", "vim.version.version8")
AddVersionParent("vim.version.version10", "vim.version.version9")
AddVersionParent("vim.version.version10", "vim.version.version6")
AddVersionParent("vim.version.version10", "vim.version.version7")
AddVersionParent("vim.version.version10", "vim.version.version1")
AddVersionParent("vim.version.version10", "vim.version.version4")
AddVersionParent("vim.version.version10", "vim.version.version5")
AddVersionParent("vim.version.version10", "vim.version.version2")
AddVersionParent("vim.version.version10", "vim.version.version3")
AddVersionParent("vim.version.version10", "vmodl.version.version0")
AddVersionParent("vim.version.version10", "vmodl.version.version1")
AddVersionParent("vim.version.version10", "vmodl.version.version2")
AddVersionParent("vim.version.version10", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version10", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version10", "vim.version.version10")
AddVersionParent("vim.version.version11", "vmodl.query.version.version4")
AddVersionParent("vim.version.version11", "vmodl.query.version.version3")
AddVersionParent("vim.version.version11", "vmodl.query.version.version2")
AddVersionParent("vim.version.version11", "vmodl.query.version.version1")
AddVersionParent("vim.version.version11", "vim.version.version8")
AddVersionParent("vim.version.version11", "vim.version.version9")
AddVersionParent("vim.version.version11", "vim.version.version6")
AddVersionParent("vim.version.version11", "vim.version.version7")
AddVersionParent("vim.version.version11", "vim.version.version1")
AddVersionParent("vim.version.version11", "vim.version.version4")
AddVersionParent("vim.version.version11", "vim.version.version5")
AddVersionParent("vim.version.version11", "vim.version.version2")
AddVersionParent("vim.version.version11", "vim.version.version3")
AddVersionParent("vim.version.version11", "vmodl.version.version0")
AddVersionParent("vim.version.version11", "vmodl.version.version1")
AddVersionParent("vim.version.version11", "vmodl.version.version2")
AddVersionParent("vim.version.version11", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version11", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version11", "vim.version.version10")
AddVersionParent("vim.version.version11", "vim.version.version11")
AddVersionParent("vim.version.version12", "vmodl.query.version.version4")
AddVersionParent("vim.version.version12", "vmodl.query.version.version3")
AddVersionParent("vim.version.version12", "vmodl.query.version.version2")
AddVersionParent("vim.version.version12", "vmodl.query.version.version1")
AddVersionParent("vim.version.version12", "vim.version.version8")
AddVersionParent("vim.version.version12", "vim.version.version9")
AddVersionParent("vim.version.version12", "vim.version.version6")
AddVersionParent("vim.version.version12", "vim.version.version7")
AddVersionParent("vim.version.version12", "vim.version.version1")
AddVersionParent("vim.version.version12", "vim.version.version4")
AddVersionParent("vim.version.version12", "vim.version.version5")
AddVersionParent("vim.version.version12", "vim.version.version2")
AddVersionParent("vim.version.version12", "vim.version.version3")
AddVersionParent("vim.version.version12", "vmodl.version.version0")
AddVersionParent("vim.version.version12", "vmodl.version.version1")
AddVersionParent("vim.version.version12", "vmodl.version.version2")
AddVersionParent("vim.version.version12", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version12", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version12", "vim.version.version10")
AddVersionParent("vim.version.version12", "vim.version.version11")
AddVersionParent("vim.version.version12", "vim.version.version12")

newestVersions.Add("cis.data.provider.version.version13")
stableVersions.Add("cis.data.provider.version.version13")
publicVersions.Add("cis.data.provider.version.version13")
dottedVersions.Add("cis.data.provider.version.version13")
oldestVersions.Add("cis.data.provider.version.version1")

CreateDataType("cis.data.provider.BatchQuerySpec", "DPBatchQuerySpec", "vmodl.DynamicData", "cis.data.provider.version.version1", [("querySpecs", "cis.data.provider.QuerySpec[]", "cis.data.provider.version.version1", F_OPTIONAL)])
CreateDataType("cis.data.provider.BatchResultSet", "DPBatchResultSet", "vmodl.DynamicData", "cis.data.provider.version.version1", [("resultSets", "cis.data.provider.ResultSet[]", "cis.data.provider.version.version1", F_OPTIONAL)])
CreateDataType("cis.data.provider.Filter", "DPFilter", "vmodl.DynamicData", "cis.data.provider.version.version1", [("criteria", "cis.data.provider.PropertyPredicate[]", "cis.data.provider.version.version1", 0), ("operator", "string", "cis.data.provider.version.version1", F_OPTIONAL)])
CreateEnumType("cis.data.provider.Filter.LogicalOperator", "DPFilterLogicalOperator", "cis.data.provider.version.version1", ["AND", "OR"])
CreateDataType("cis.data.provider.OptionalPropertyValue", "DPOptionalPropertyValue", "vmodl.DynamicData", "cis.data.provider.version.version1", [("value", "anyType", "cis.data.provider.version.version1", F_OPTIONAL)])
CreateDataType("cis.data.provider.PropertyPredicate", "DPPropertyPredicate", "vmodl.DynamicData", "cis.data.provider.version.version1", [("property", "string", "cis.data.provider.version.version1", 0), ("operator", "string", "cis.data.provider.version.version1", 0), ("comparableValue", "anyType", "cis.data.provider.version.version1", F_OPTIONAL), ("comparableList", "anyType[]", "cis.data.provider.version.version1", F_OPTIONAL), ("ignoreCase", "boolean", "cis.data.provider.version.version1", F_OPTIONAL)])
CreateEnumType("cis.data.provider.PropertyPredicate.ComparisonOperator", "DPPropertyPredicateComparisonOperator", "cis.data.provider.version.version1", ["EQUAL", "NOT_EQUAL", "GREATER", "GREATER_OR_EQUAL", "LESS", "LESS_OR_EQUAL", "IN", "LIKE", "UNSET"])
CreateDataType("cis.data.provider.QuerySpec", "DPQuerySpec", "vmodl.DynamicData", "cis.data.provider.version.version1", [("properties", "string[]", "cis.data.provider.version.version1", F_OPTIONAL), ("resourceModel", "string", "cis.data.provider.version.version1", 0), ("filter", "cis.data.provider.Filter", "cis.data.provider.version.version1", F_OPTIONAL), ("sortCriteria", "cis.data.provider.SortCriterion[]", "cis.data.provider.version.version1", F_OPTIONAL), ("offset", "int", "cis.data.provider.version.version1", F_OPTIONAL), ("limit", "int", "cis.data.provider.version.version1", F_OPTIONAL), ("returnTotalCount", "boolean", "cis.data.provider.version.version1", F_OPTIONAL)])
CreateDataType("cis.data.provider.ResourceItem", "DPResourceItem", "vmodl.DynamicData", "cis.data.provider.version.version1", [("propertyValues", "cis.data.provider.OptionalPropertyValue[]", "cis.data.provider.version.version1", 0)])
CreateManagedType("cis.data.provider.ResourceModel", "DPResourceModel", "vmodl.ManagedObject", "cis.data.provider.version.version1", None, [("query", "Query", "cis.data.provider.version.version1", (("querySpec", "cis.data.provider.QuerySpec", "cis.data.provider.version.version1", 0, None),), (0, "cis.data.provider.ResultSet", "cis.data.provider.ResultSet"), "System.View", None), ("queryBatch", "QueryBatch", "cis.data.provider.version.version1", (("queryBatch", "cis.data.provider.BatchQuerySpec", "cis.data.provider.version.version1", 0, None),), (0, "cis.data.provider.BatchResultSet", "cis.data.provider.BatchResultSet"), "System.View", None), ("getSchema", "GetSchema", "cis.data.provider.version.version1", (), (0, "cis.data.provider.schema.ResourceModelInfo[]", "cis.data.provider.schema.ResourceModelInfo[]"), "System.View", None)])
CreateDataType("cis.data.provider.ResultSet", "DPResultSet", "vmodl.DynamicData", "cis.data.provider.version.version1", [("properties", "string[]", "cis.data.provider.version.version1", F_OPTIONAL), ("items", "cis.data.provider.ResourceItem[]", "cis.data.provider.version.version1", F_OPTIONAL), ("totalCount", "long", "cis.data.provider.version.version1", F_OPTIONAL)])
CreateDataType("cis.data.provider.SortCriterion", "DPSortCriterion", "vmodl.DynamicData", "cis.data.provider.version.version1", [("property", "string", "cis.data.provider.version.version1", 0), ("sortDirection", "string", "cis.data.provider.version.version1", F_OPTIONAL), ("ignoreCase", "boolean", "cis.data.provider.version.version1", F_OPTIONAL)])
CreateEnumType("cis.data.provider.SortCriterion.SortDirection", "DPSortCriterionSortDirection", "cis.data.provider.version.version1", ["ASCENDING", "DESCENDING"])
CreateDataType("cis.data.provider.schema.PropertyInfo", "DPSchemaPropertyInfo", "vmodl.DynamicData", "cis.data.provider.version.version1", [("name", "string", "cis.data.provider.version.version1", 0), ("filterable", "boolean", "cis.data.provider.version.version1", F_OPTIONAL), ("filterableByUnset", "boolean", "cis.data.provider.version.version1", F_OPTIONAL), ("type", "string", "cis.data.provider.version.version1", F_OPTIONAL)])
CreateEnumType("cis.data.provider.schema.PropertyInfo.PropertyType", "DPSchemaPropertyInfoPropertyType", "cis.data.provider.version.version1", ["STRING", "BYTE", "SHORT", "INT", "LONG", "FLOAT", "DOUBLE", "BOOLEAN", "MOREF", "ENUM"])
CreateDataType("cis.data.provider.schema.ResourceModelInfo", "DPSchemaResourceModelInfo", "vmodl.DynamicData", "cis.data.provider.version.version1", [("name", "string", "cis.data.provider.version.version1", 0), ("properties", "cis.data.provider.schema.PropertyInfo[]", "cis.data.provider.version.version1", 0)])
